### PR TITLE
Change /connection state to omit 'mine'

### PR DESCRIPTION
**Pull request by karth295**
This branch is live on https://tawk.space. I don't understand why I needed the `delete o.key`, though.

### CODE REVIEW

**Comment by toomim** [comment]
I think the `delete o.key` actually addresses a general security bug in statebus. For example, if you do on client:

``` javascript
save({key: '/connection', users: {key: '/users', ...<your own passwords>}})
```

...then the server will try to save that connection with this code:

``` javascript
master.save(connection)
```

And that will save the new users into the master bus, which controls authentication.

We should address this more. I think that it is solved best after we implement the new JSON format, which will let statebus distinguish keys in objects automatically, which might be a nice way to automatically plug these security holes.

**Comment by toomim** [comment]
Karthik how did you notice that the delete o.key was necessary?

**Comment by karth295** [comment]
After doing the `master.save(connection)` I think everybody who did `fetch(/connection)` ended up with the same connection. That surprised me because there is an explicit `to_fetch` function for the `/connection` on the server bus.

**Comment by toomim** [comment]
Ah, yes, it was surprising I imagine because you'd think the `to_fetch` function should define the state, and not allow anyone to change it? I've had that thought too... and I'm interested in changing statebus to enforce that behavior!

**Comment by karth295** [comment]
Yeah. If you have a `to_fetch` handler, you should also have to write a `to_save` handler. The default `to_save` handler if you already have `to_fetch` should be a no-op (or error if that is part of the protocol).

I was thinking about that with respect to some of my computed client state. I have `groups/<gid>` for looking up group -> members. It's computed from `/connections`, which is a mapping from member -> group. I could write a bug where I save over `groups/<gid>` and break that model.

**Pull request merged**
